name: Automated data update

on:
  schedule:
    - cron: "0 17 * * *"
  push:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python3
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'

    - name: Fetch latest data from SF DPH
      uses: mohamedMok/httpie.action@master
      with:
        args: GET www.sfdph.org/dph/alerts/coronavirus.asp

    - name: Install required python libraries
      run: pip install pandas matplotlib

    - name: Troubleshooting
      run: find $HOME

    - name: Execute the script to update
      run: python ./update-covid-19.py /home/runner/work/_temp/_github_home/swintonhttpieaction.response.body
        
    - name: Commit the changed files
      uses: actions-go/push@v1
      with:
        commit-message: '[automatic] update covid-19 csv and figure'
